/**
 * Razorpay Payment Integration Service
 * 
 * This service handles Razorpay payment processing for subscription plans.
 * 
 * Environment Variables Required:
 * - VITE_RAZORPAY_KEY_ID: Your Razorpay Key ID
 * - VITE_RAZORPAY_KEY_SECRET: Your Razorpay Key Secret (for backend only)
 */

// Load Razorpay script dynamically
const loadRazorpayScript = (): Promise<void> => {
  return new Promise((resolve, reject) => {
    if (window.Razorpay) {
      resolve()
      return
    }

    const script = document.createElement("script")
    script.src = "https://checkout.razorpay.com/v1/checkout.js"
    script.async = true
    script.onload = () => resolve()
    script.onerror = () => reject(new Error("Failed to load Razorpay script"))
    document.body.appendChild(script)
  })
}

export interface RazorpayOptions {
  key: string
  amount: number // Amount in paise (smallest currency unit)
  currency: string
  name: string
  description: string
  image?: string // Merchant logo URL
  order_id?: string // If order is created on backend
  prefill?: {
    name?: string
    email?: string
    contact?: string
  }
  notes?: Record<string, string>
  theme?: {
    color?: string
  }
  handler?: (response: RazorpayResponse) => void
  modal?: {
    ondismiss?: () => void
  }
}

export interface RazorpayResponse {
  razorpay_payment_id: string
  razorpay_order_id: string
  razorpay_signature: string
}

export interface CreateOrderOptions {
  amount: number // Amount in paise
  currency?: string
  receipt?: string
  notes?: Record<string, string>
}

/**
 * Initialize Razorpay checkout
 */
export async function initializeRazorpay(): Promise<void> {
  await loadRazorpayScript()
}

/**
 * Create a Razorpay order (optional - can be done on backend)
 * For now, we'll create orders directly on frontend
 */
export async function createRazorpayOrder(options: CreateOrderOptions): Promise<string> {
  const RAZORPAY_KEY_ID = import.meta.env.VITE_RAZORPAY_KEY_ID
  const RAZORPAY_KEY_SECRET = import.meta.env.VITE_RAZORPAY_KEY_SECRET

  if (!RAZORPAY_KEY_ID) {
    throw new Error("Razorpay Key ID is not configured. Set VITE_RAZORPAY_KEY_ID in your .env file")
  }

  // Note: In production, order creation should be done on backend for security
  // This is a simplified version for frontend-only implementation
  // For production, create an API endpoint that uses RAZORPAY_KEY_SECRET
  
  // For now, we'll use Razorpay's direct payment flow without pre-creating orders
  // The order_id will be generated by Razorpay automatically
  return Promise.resolve("")
}

/**
 * Open Razorpay checkout
 */
export async function openRazorpayCheckout(
  options: Omit<RazorpayOptions, "key">,
  onSuccess: (response: RazorpayResponse) => void | Promise<void>,
  onError?: (error: Error) => void
): Promise<void> {
  try {
    await initializeRazorpay()

    const RAZORPAY_KEY_ID = import.meta.env.VITE_RAZORPAY_KEY_ID
    if (!RAZORPAY_KEY_ID) {
      throw new Error("Razorpay Key ID is not configured. Set VITE_RAZORPAY_KEY_ID in your .env file")
    }

    const razorpayOptions: RazorpayOptions = {
      ...options,
      key: RAZORPAY_KEY_ID,
      handler: async (response: RazorpayResponse) => {
        try {
          await onSuccess(response)
        } catch (error) {
          console.error("Error in payment success handler:", error)
          if (onError) {
            onError(error instanceof Error ? error : new Error(String(error)))
          }
        }
      },
      modal: {
        ondismiss: () => {
          if (onError) {
            onError(new Error("Payment cancelled by user"))
          }
        },
      },
    }

    const razorpay = new window.Razorpay(razorpayOptions)
    razorpay.open()
  } catch (error) {
    console.error("Error opening Razorpay checkout:", error)
    if (onError) {
      onError(error instanceof Error ? error : new Error(String(error)))
    }
  }
}

/**
 * Verify Razorpay payment signature (should be done on backend)
 * For now, we'll trust Razorpay's response and verify on backend
 */
export async function verifyPaymentSignature(
  orderId: string,
  paymentId: string,
  signature: string
): Promise<boolean> {
  // In production, this should be done on your backend
  // For now, we'll return true and let the backend verify
  // You should create an API endpoint that uses RAZORPAY_KEY_SECRET to verify
  
  // Example backend verification (Node.js):
  // const crypto = require('crypto');
  // const hmac = crypto.createHmac('sha256', RAZORPAY_KEY_SECRET);
  // hmac.update(orderId + '|' + paymentId);
  // const generatedSignature = hmac.digest('hex');
  // return generatedSignature === signature;
  
  return true
}

// Extend Window interface for Razorpay
declare global {
  interface Window {
    Razorpay: new (options: RazorpayOptions) => {
      open: () => void
      on: (event: string, handler: (data: any) => void) => void
    }
  }
}

